eventex/subscriptions/urls.py
from django.urls import path

from eventex.subscriptions.views import new, detail

app_name = 'subscriptions'

urlpatterns = [
    path('', new, name='new'),
    path('<uuid:subscription_id>/', detail, name='detail'),
]

eventex/urls.py
from django.contrib import admin
from django.urls import path, include

from eventex.core.views import speaker_detail, talk_list, HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('subscriptions/', include('eventex.subscriptions.urls')),
    path('talks/', talk_list, name='talk_list'),
    path('speakers/<slug:slug>/', speaker_detail, name='speaker_detail'),
    path('admin/', admin.site.urls),
]

eventex/core/models.py
from enum import IntEnum

from django.db import models
from django.shortcuts import resolve_url as r

from eventex.core.manages import KindQuerySet, PeriodManager


class ContactTypes(IntEnum):
    EMAIL = 0,
    PHONE = 1,

    @classmethod
    def choices(cls):
        return [(key.value, key.name) for key in cls]


class Speaker(models.Model):
    name = models.CharField('nome', max_length=255)
    slug = models.SlugField('slug')
    photo = models.URLField('foto')
    website = models.URLField('website', blank=True)
    description = models.TextField('descrição', blank=True)

    class Meta:
        verbose_name = 'palestrante'
        verbose_name_plural = 'palestrantes'

    def get_absolute_url(self):
        return r('speaker_detail', slug=self.slug)

    def __str__(self):
        return self.name


class Contact(models.Model):
    EMAIL = ContactTypes.EMAIL
    PHONE = ContactTypes.PHONE

    speaker = models.ForeignKey('Speaker', on_delete=models.CASCADE,
                                verbose_name='palestrante')
    kind = models.IntegerField('tipo', choices=ContactTypes.choices(),
                               default=ContactTypes.EMAIL)
    value = models.CharField('valor', max_length=255)

    # objects = KindContactManager()
    objects = KindQuerySet.as_manager()

    class Meta:
        verbose_name = 'contato'
        verbose_name_plural = 'contatos'

    def __str__(self):
        return self.value


"""
Abstract Base Class ABC - This class will not be created on database

Example of ABC use
>>
class Activity(models.Model):
    title = models.CharField('título', max_length=200)
    start = models.TimeField('hora início', blank=True, null=True)
    description = models.TextField('descrição', blank=True, null=True)
    speakers = models.ManyToManyField('Speaker', blank=True,
                                      verbose_name='palestrantes')

    objects = PeriodManager()

    class Meta:
        abstract = True  # Indicates that the class is an abstract model
        ordering = ['start']
        verbose_name = 'palestra'
        verbose_name_plural = 'palestras'

    def __str__(self):
        return f'{self.start} {self.title}'


class Talk(Activity):
    pass
>>
"""


class Talk(models.Model):
    title = models.CharField('título', max_length=200)
    start = models.TimeField('hora início', blank=True, null=True)
    description = models.TextField('descrição', blank=True, null=True)
    speakers = models.ManyToManyField('Speaker', blank=True,
                                      verbose_name='palestrantes')

    objects = PeriodManager()

    class Meta:
        ordering = ['start']
        verbose_name = 'palestra'
        verbose_name_plural = 'palestras'

    def __str__(self):
        return f'{self.start} {self.title}'


"""
Example of migration from ABC to MTI models
"""


# class CourseOld(Activity):
#     slots = models.IntegerField('lugares')
#
#     class Meta:
#         verbose_name = 'curso'
#         verbose_name_plural = 'cursos'
#
#     def __str__(self):
#         return f'{self.slots} {self.start} {self.title}'


class Course(Talk):
    """
    To migrate without lost data from CourseOld to Course,
    generate the migration file:

    >> ./manage.py makemigrations --empty -n course_abc_to_mti core

    """
    slots = models.IntegerField('lugares')

    objects = PeriodManager()

    class Meta:
        verbose_name = 'curso'
        verbose_name_plural = 'cursos'

    def __str__(self):
        return f'{self.slots} {self.start} {self.title}'

eventex/core/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from eventex.core.models import Speaker, Talk

# class GenericHomeView(MultipleObjectMixin, TemplateView):
""" Method already implemented by TemplateView

def get(self, *args, **kwargs):
    context = self.get_context_data()
    return self.render_to_response(context)
"""

""" Method already implemented by TemplateResponseMixin

def render_to_response(self, context):
    return render(self.request, self.template_name, context)
"""

""" Method and attributes already implemented by MultipleObjectMixin

object_list = None
context_object_name = None

def get_context_data(self, **kwargs):
    context = {self.context_object_name: self.object_list}
    context.update(kwargs)
    return context
"""


class HomeView(ListView):
    template_name = 'index.html'
    model = Speaker


def speaker_detail(request, slug):
    speaker = get_object_or_404(Speaker, slug=slug)
    return render(request, 'core/speaker/detail.html', {'speaker': speaker})


def talk_list(request):
    """
    When needs an API Mock, example:

    speaker = Speaker(
        name='Fabricio Nogueira',
        slug='fabricio-nogueira'
    )
    course = [
        dict(title='Course title',
             start='09:00',
             description='Course description',
             speakers={'all': [speaker]})
    ]
    """

    """
    Concatenate the list:

    at_morning = (
            list(Talk.objects.at_morning()) +
            list(Course.objects.at_morning())
    )
    at_morning.sort(key=lambda o: o.start)

    at_afternoon = (
            list(Talk.objects.at_afternoon()) +
            list(Course.objects.at_afternoon())
    )
    at_morning.sort(key=lambda o: o.start)
    """
    context = {
        'morning_talks': Talk.objects.at_morning(),
        'afternoon_talks': Talk.objects.at_afternoon(),
    }
    return render(request, 'core/talk/list.html', context)

eventex/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>
      {% block title %}Eventex - O maior encontro hacker do mundo!{% endblock title %}
    </title>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta
      name="description"
      content="Eventex - O maior encontro hacker do mundo!"
    />
    <meta name="author" content="wttd" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico'%}" />

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/basalstyle/style.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/main.css'%}" />
    <link
      rel="stylesheet"
      href="http://fonts.googleapis.com/css?family=Economica:400,700"
      type="text/css"
    />
  </head>

  <body>
    <div class="header-frame row">
        {% include 'nav.html' only %}
    </div>

    {%block content%} {%endblock content%}

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script src="{% static 'js/jquery-1.11.0.min.js'%}"></script>
    <script src="{% static 'js/jquery.stellar.min.js'%}"></script>
    <script src="{% static 'js/smooth-scroll.js'%}"></script>
    <script src="{% static 'js/retina-1.1.0.min.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>
  </body>
</html>

eventex/core/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Eventex - O maior encontro hacker do mundo!</title>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta
      name="description"
      content="Eventex - O maior encontro hacker do mundo!"
    />
    <meta name="author" content="Fabricio Nogueira <nogsantos@gmail.com>" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico'%}" />

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/basalstyle/style.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/main.css'%}" />

    <link
      href="http://fonts.googleapis.com/css?family=Economica:400,700"
      rel="stylesheet"
      type="text/css"
    />

  </head>

  <body>
    <!-- Header-->
    <div class="header-frame header-frame-absolute row">
      {% include 'nav.html' only %}
    </div>

    <!-- TOP -->
    <section id="top" data-stellar-background-ratio="0.5">
      <div class="countdown text-align-center row desktop-12 container">
        <h1 class="uppercase">Eventex</h1>
        <h3>Brasil</h3>
      </div>
    </section>

    <!-- Speakers-->
    <section id="speakers">
      <div class="speakers text-align-center row desktop-8 padding-bottom-2 container">
        <h2>Palestrantes Convidados</h2>
        {% for speaker in speaker_list %}
        <div class="desktop-4">
          <img src="{{speaker.photo}}" alt="{{speaker.name}}">
          <h4>
            <a href="{{ speaker.get_absolute_url }}">
              {{speaker.name}}
            </a>
          </h4>
        </div>
        {% endfor %}
      </div>
    </section>

    <!-- OVERVIEW -->
    <section id="overview">
      <div
        class="overview text-align-center row desktop-12 min-h-15 padding-top-2 container"
      >
        <i class="fa fa-5x fa-globe"></i>
        <h2>A Conferência</h2>
        <p class="lead">
          A maior reunião de hackers do mundo.<br />Reunindo profissionais e
          entusiastas dos quatro <br />cantos do planeta, o <em>Eventex</em> é o
          lugar onde você precisa estar.
        </p>
        <p>
          <a class="btn-basic btn-blue" data-scroll href="#register"
            >Garanta a sua vaga!</a
          >
        </p>
      </div>
    </section>

    <!-- SPONSORS -->
    <section id="sponsors">
      <div
        class="sponsors text-align-center row desktop-12 min-h-28 padding-bottom-2 container"
      >
        <h2>Patrocinadores</h2>

        <h3>Gold</h3>
        <div class="sponsor-slider min-h-6">
          <img
            class="img-responsive"
            src="{% static 'img/sponsor-gold-01.png'%}"
            alt="logo"
          />
          <img
            class="img-responsive"
            src="{% static 'img/sponsor-gold-02.png'%}"
            alt="logo"
          />
          <img
            class="img-responsive"
            src="{% static 'img/sponsor-gold-03.png'%}"
            alt="logo"
          />
        </div>

        <h3>Silver</h3>
        <div class="sponsor-slider min-h-6 margin-bottom-1">
          <img
            class="img-responsive"
            src="{% static 'img/sponsor-silver-01.png'%}"
            alt="logo"
          />
          <img
            class="img-responsive"
            src="{% static 'img/sponsor-silver-02.png'%}"
            alt="logo"
          />
          <img
            class="img-responsive"
            src="{% static 'img/sponsor-silver-03.png'%}"
            alt="logo"
          />
          <img
            class="img-responsive"
            src="{% static 'img/sponsor-silver-04.png'%}"
            alt="logo"
          />
          <img
            class="img-responsive"
            src="{% static 'img/sponsor-silver-05.png'%}"
            alt="logo"
          />
          <img
            class="img-responsive"
            src="{% static 'img/sponsor-silver-06.png'%}"
            alt="logo"
          />
        </div>

        <h3>Seja um patrocinador</h3>
        <p>Interessado? Descubra as oportunidades e benefícios.</p>
        <a
          class="btn-basic btn-blue"
          href="mailto:contato@eventex.com.br?Subject=Patrocínio"
          >informe-se</a
        >
      </div>
    </section>

    <!-- REGISTER -->
    <section id="register">
      <div class="register row">
        <div
          class="text-align-center row desktop-12 padding-top-2 min-h-14 container"
        >
          <h2>Inscrição</h2>
          <h3>Inscrições abertas!</h3>
          <a class="btn-basic btn-blue" href="{% url 'subscriptions:new' %}"
            >Inscreva-se j&aacute;!</a
          >
        </div>
      </div>
    </section>

    <!-- VENUE -->
    <section id="venue">
      <div class="row min-h-10">
        <div id="map-canvas"></div>
        <div class="row desktop-12 container">
          <div class="venue row">
            <div class="venue-address desktop-4 gutter">
              <h2>Bar Samba Caffé</h2>
              <p>Melhor que qualquer centro de convenções.</p>
              <p class="address">
                <i class="fa fa-2x fa-map-marker fa-inverse"></i>
                Rua do Ouvidor 23, Centro<br />
                Rio de Janeiro, RJ
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

   <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

    <script src="{% static 'js/jquery-1.11.0.min.js'%}"></script>
    <script src="{% static 'js/jquery.stellar.min.js'%}"></script>
    <script src="{% static 'js/smooth-scroll.js'%}"></script>
    <script src="{% static 'js/retina-1.1.0.min.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>
  </body>
</html>

eventex/core/templates/nav.html
<header class="header header-inline min-h-3 row desktop-12 container" role="banner">
    <div class="site-logo">
        <h1><a href="{% url 'home' %}" rel="home">Eventex</h1>
        <p class="site-description screen-reader-only">O maior encontro hacker do mundo!</p>
    </div>

    <nav class="nav-inline" role="navigation">
        <a href="javascript:void(0);" class="nav-mobile"><i class="fa fa-bars"></i></a>
        <ul>
            <li><a data-scroll href="{% url 'home' %}#overview">Conferência</a></li>
            <li><a data-scroll href="{% url 'talk_list' %}">Palestras</a></li>
            <li><a data-scroll href="{% url 'home' %}#speakers">Palestrantes</a></li>
            <li><a data-scroll href="{% url 'home' %}#sponsors">Patrocinadores</a></li>
            <li><a data-scroll href="{% url 'home' %}#register">Inscrição</a></li>
            <li><a data-scroll href="{% url 'home' %}#venue">Local</a></li>
        </ul>
    </nav>

</header>